final List<String> activities = [
  'Watch anime',
  'Read manga',
  'Join an anime club',
  'Attend an anime convention',
  'Cosplay as your favorite character',
  'Create fan art',
  'Write fan fiction',
  'Learn Japanese',
  'Explore anime merchandise',
  'Discuss anime with friends',
  'Stream anime online',
  'Collect anime figures',
  'Play anime-themed games',
  'Follow anime news and updates',
  'Engage in online anime communities',
  'Create an anime blog or vlog',
  'Participate in anime challenges',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
  'Host an anime watch party Explore anime soundtracks',
];
